spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lliyuu520/spring-boot-study.git
          search-paths: config-repo
#      label: master
server:
  port: 8080
